# Generated by Django 4.2.20 on 2025-04-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightid', models.CharField(max_length=10)),
                ('flight_name', models.CharField(max_length=100)),
                ('starting_from', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_seats', models.IntegerField()),
                ('total_seats', models.IntegerField()),
                ('flight_type', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], max_length=50)),
                ('flight_supply', models.CharField(choices=[('airline', 'Airline'), ('charter', 'Charter')], max_length=100)),
                ('flight_status', models.CharField(choices=[('on_time', 'On Time'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], max_length=50)),
            ],
        ),
    ]
